### ISSUE TITLE
Specify default model

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/ChatGptNet#10]
Add a property to `ChatGptOptions` that allows to specify default model for chat completion, default to **gpt-3.5-turbo**. If no value is specified in the **AskAsync** method, the default model must be used.

**Comment by nanny07** [comment]
Hi Marco, what do you want to call the new property? I was thinking about "ChatGptModelDefault"

**Comment by marcominerva** [comment]
I think that just **DefaultModel** should be fine.
