### ISSUE TITLE
Invalid null check in AzureChatGptServiceConfiguration.cs

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/ChatGptNet#122]
I noticed a problem in the two lines of code mentioned in the 2 links below
- https://github.com/marcominerva/ChatGptNet/blob/master/src/ChatGptNet/ServiceConfigurations/AzureChatGptServiceConfiguration.cs#L67

- https://github.com/marcominerva/ChatGptNet/blob/master/src/ChatGptNet/ServiceConfigurations/AzureChatGptServiceConfiguration.cs#L81

The problem is the following: the first "ArgumentNullException.ThrowIfNull" argument is the parameter that will be checked for nullability.
By passing a "nameof()" as parameter that value will never be null.

The signature of the "ArgumentNullException.ThrowIfNull" method is the following

public static void ThrowIfNull(object? argument, string? paramName = null)

Actually I found this problem only in the file mentioned in the title.
Can I solve this issue?

**Comment by marcominerva** [comment]
I think the problems are related to a bad copy/paste. I have assigned the issue to you, feel free to make a PR.
