### ISSUE TITLE
Missing call to 'cancellationToken.ThrowIfCancellationRequested' method

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/ChatGptNet#130]
I noticed that the async methods who have a CancellationToken parameter don't have the call to ThrowIfCancellationRequested method.

Is this a missing instruction or this method is called somewhere else?
If this is a missing instruction can I take care of this issue?

Hope I've explained the issue correctly

**Comment by marcominerva** [comment]
Can you show an example of the code you're referring to?

**Comment by marcominerva** [comment]
When there is an async call, like `cache.SetAsync` (or `httpClient.PostAsync` in another methods), The Cancellation Token is forwaded to them, so them are in charge to handle the cancellation. There is no need to explicitly use the ThrowIfCancellationRequested method in such situations.

**Comment by N1K0232** [comment]
Oh. Okay thank you so much.
I thought that calling that method was necessary.

I'm sorry for creating the issue. Next time I'll ask directly in Discussion section to avoid unnecessary issues

**Comment by marcominerva** [comment]
You don't have to excuse, issues are here to talk about the code 😀
