### ISSUE TITLE
How to get the chatgpt's response for the Added Function response in 'AddFunctionResponseAsync' ?

### ISSUE THREAD

**Issue by Gopichandar** [marcominerva/ChatGptNet#131]
On this [example](https://github.com/marcominerva/ChatGptNet/blob/b6553762672861411dcf64e24f8990b728659941/samples/ChatGptFunctionCallingConsole/Application.cs#L110C23-L110C23),  I'm not sure how can I get the response for the added function call, 

I mean how can get the 'second_response' as mentioned in the open AI [documentation](https://platform.openai.com/docs/guides/function-calling/parallel-function-calling)? 

```
 # Step 4: send the info for each function call and function response to the model
        for tool_call in tool_calls:
            function_name = tool_call.function.name
            function_to_call = available_functions[function_name]
            function_args = json.loads(tool_call.function.arguments)
            function_response = function_to_call(
                location=function_args.get("location"),
                unit=function_args.get("unit"),
            )
            messages.append(
                {
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": function_response,
                }
            )  # extend conversation with function response
        second_response = client.chat.completions.create(
            model="gpt-3.5-turbo-1106",
            messages=messages,
        )  # get a new response from the model where it can see the function response
        return second_response
```

Can you help me on this?

**Comment by marcominerva** [comment]
At this moment, the library does not support parallel function calling.

**Comment by Gopichandar** [comment]
Hi @marcominerva ,  Thanks for the response, but the question is not about the 'Parallel Function calling',  

The conversation will be like this: 

```
Assistant:  How can I help you? 
User: What is the weather like in Taggia?
Function: [function_response of get weatherforecast]
```
Now, after the function call response, how can I 'Ask' for the response?  Do I need to send the same 'User' question again in the conversation?

**Comment by marcominerva** [comment]
You need to manually call the function (for example using an `HttpClient`), then you just need to call the `AddFunctionResponseAsync` method, passing the result you have obtained from the function.

**Comment by Gopichandar** [comment]
Hi @marcominerva , after passing the obtained from the function to `AddFunctionResponseAsync`, what will be the next step? How to get the response for 'AddFunctionResponseAsync' from chatgpt?

**Comment by Gopichandar** [comment]
I'm asking about the  'second_response' after the `tool_call`, how can I get the 'second_response' from the `chatgptClient` ?

```
for tool_call in tool_calls:
            function_name = tool_call.function.name
            function_to_call = available_functions[function_name]
            function_args = json.loads(tool_call.function.arguments)
            function_response = function_to_call(
                location=function_args.get("location"),
                unit=function_args.get("unit"),
            )
            messages.append(
                {
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": function_response,
                }
            )  # extend conversation with function response
        second_response = client.chat.completions.create(
            model="gpt-3.5-turbo-1106",
            messages=messages,
```

**Comment by marcominerva** [comment]
`AddFunctionResponseAsync` does not return a value, it simply adds the response (that you have already obtained via the `HttpClient`, for example) to the conversation history, so the next step is just to continue the conversation, i.e. call the `AskAsync` method again.

**Comment by Gopichandar** [comment]
So, we need to call the `AskAsync` again with the same question that user asked, Right @marcominerva ? 

Assistant:  How can I help you? 
User: What is the weather like in Taggia?
Function: {"Taggia": "cold"} 
User: What is the weather like in Taggia? 
Assistant: It is cold in Taggia. 

I think we need to have a way to send the conversations again after adding the Function response  (or) maybe `AddFunctionResponseAsync` should return the response.  Because the OpenAI examples clearly sent the conversation again and it was not add the user question again.  Please suggest

**Comment by marcominerva** [comment]
No, you need to explicitly call the function that you get, then add the response text (for example, "The weather in Taggia is fine", that is the response of the function that you obtain using an `HttpClient`) using `AddFunctionResponseAsync`.

**Comment by Gopichandar** [comment]
But How can we predict the user intent @marcominerva? I feel we need to share the data via `FunctionCall` to chatgpt and chatgpt should respond based on the user intent.
```
Assistant:  How can I help you? 
User:  where the weather is 'cold '?   Taggia (or) Snag
Function: The weather in Taggia is cold
Function: The weather in Snag is hot 
User: I'm asking where it is 'cold '?
```

**Comment by marcominerva** [comment]
Try to run the sample. You'll see that ChatGptNet will return the name and the parameters of the function to call.

**Comment by Gopichandar** [comment]
Hi @marcominerva ,  After running here is the result. 

![image](https://github.com/marcominerva/ChatGptNet/assets/13073344/99d542de-2276-4932-a0fb-08e3c8929983)

**Comment by marcominerva** [comment]
Yes, it shows that ChatGptNet is telling you to call a function that has the name `GetWeatherForecast`.

**Comment by Gopichandar** [comment]
Hi @marcominerva ,  I got the point that it is calling the function named 'GetWeatherForecast'.  Problem is with the answer "It is Bracing in rania, with 13 degrees" which is not inline with he question. 

Workflow should be `User Question -> FuntionCall Data -> Assitant Answer -> User question` and should NOT be like `User Question -> FuntionCall Answer-> User Question`.

**Comment by marcominerva** [comment]
This is just an example of the workflow. In a real scenario, you need to better define the function definitions and, of course, call a function that gives a real answer.

**Comment by Gopichandar** [comment]
I would say we need to have a way something like SendAsync(Guid conversationId)` which would internally get the `messages` from the cache and then send it to chatgpt api and return back the `ChatGptResponse`.

**Comment by marcominerva** [comment]
So, you can make a PR 😉

**Comment by Gopichandar** [comment]
Sure, will do @marcominerva
