### ISSUE TITLE
Add streaming support

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/ChatGptNet#27]
Chat completion API supports response streaming: https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream. We need to think about how to add this feature to **ChatGptNet**. 

An idea can be a method like this (with all the related overloads):

```
IAsyncEnumerable<ChatGptResponse> AskStreamAsync(string message);
```

**Comment by totti240282** [comment]
I think it's the most correct solution to receive the data as they arrive.
