### ISSUE TITLE
Add Blazor samples

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/ChatGptNet#34]
It would be great to have one or more samples that show how to integrate the **ChatGptNet** library in Blazor projects.

**Comment by nicolaparo** [comment]
I like the idea. Should we think about implementing it with Blazor Server or Blazor Wasm? The main difference would be that in Blazor Server we can actually inject the service directly into the page, meanwhile in Wasm we have to go though an API layer, unless the openai api supports also the CORS.

**Comment by marcominerva** [comment]
@nicolaparo, you're welcome if you want to work on the current samples! Can I assign this issue to you?

**Comment by nicolaparo** [comment]
Yes, with pleasure! Also, since the two implementations are almost identical, should we start to focus mainly on Blazor Wasm?

**Comment by marcominerva** [comment]
Great, I have assigned the issue to you :-) Yes, let's start with Blazor Wasm, it makes sense.
