### ISSUE TITLE
Add the support for a factory class

### ISSUE THREAD

**Issue by nicolaparo** [marcominerva/ChatGptNet#43]
Sometimes the exact options for creating an instance of an `IChatGptClient` might not be known at the application startup. 

This might be the case, for example, when the application has to provide access to the functionality using a user-supplied api key obtained at the runtime. 

By implementing a `IChatGptClientFactory` we can enable the support for such functionality.

We might, for example, enable the possibility to add this service to our application by doing
```csharp
builder.Services.AddChatGptClientFactory(options =>
{
    options.DefaultModel = ChatGptModels.Gpt35Turbo;  // Default: ChatGptModels.Gpt35Turbo
    options.MessageLimit = 16;  // Default: 10
    options.MessageExpiration = TimeSpan.FromMinutes(5);    // Default: 1 hour
});
```

And then we can obtain a new `IChatGptClient` with
```csharp
public class MyExampleService
{
    private readonly IChatGptClientFactory factory;

    public MyExampleService(IChatGptClientFactory factory)
    {
        this.factory = factory;
    }

    public async Task DoSomethingWithUserTokenAsync(string userSuppliedApiKey)
    {
        var chatGptClient = factory.CreateClient(options => {
            options.ApiKey = userSuppliedApiKey
        });
        // do something
    }
}
```

**Comment by marcominerva** [comment]
Actually, if you need to provide settings like the API Key at runtime, you can use the `AddChatGpt` overload that provides an `IServiceProvider` and that is invoked for every request. With that, you can set all the ChatGptOptions you need.

**Comment by nicolaparo** [comment]
Yes, the overload that accepts the `IServiceProvider` as a parameter can be the solution for most of the cases. However, the scenario I was actually thinking about is within a Blazor Wasm application, where the user can supply his own token in a text input. A factory class can enable a developer to inject an `IChatGptClientFactory` object into the page. Then, at the runtime, when the user visits the page and inserts their own key, a new `IChatGptClient` is created via the factory method.

**Comment by marcominerva** [comment]
It is an interesting scenario 😀 So, would you like to take care of this implementation?

**Comment by nicolaparo** [comment]
Sure!
