### ISSUE TITLE
Add a method to estimate token count

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/ChatGptNet#5]
ChatGPT pricing is based on tokens. It would be useful to have a method to estimate the token count for a given message and for the current cached conversation. Something like that:

```
 // For a single message.
Task<int> GetEstimatedTokenCountAsync(string nessage);   

// For the current cached conversation and the new message.
Task<int> GetEstimatedTokenCountAsync(Guid conversationId, string nessage);
```

The count must be done at client-side, following this guide: https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them.

The result just need to be an estimate, it needn't to be 100% accurate, given that the algorithm used by OpenAI to calculate token may change in future. To give an idea if the algorithm is performing well, we can use the official tool available at https://platform.openai.com/tokenizer to check the results.

**Comment by nicolaparo** [comment]
There are multiple possibilities to perform this operation:

A possible implementation (I tried) is to port to C# the code that is implemented in https://github.com/latitudegames/GPT-3-Encoder (this repository is referenced in the tokenizer tool from OpenAI as a programmatic interface to use). 
By some tests with the porting of the library in C#, I encountered these issues:
- It requires additional resources (`vocab.bpe` - 500kB and `encoder.json` - 1MB files) other than a single piece of code, that would make the library heavier
- It seems to work correctly only with English language, as the `vocab.bpe` and the `encoder.json` files referenced in the repo are only for English.
- I'm not sure about adding `vocab.bpe` and `encoder.json` files for each language to this repository only for estimating the token count.


Another implementation can be a simple algorithm that follows the "rule of thumb" described in the tokenizer tool:
> A helpful rule of thumb is that one token generally corresponds to ~4 characters of text for common English text. This translates to roughly ¾ of a word (so 100 tokens ~= 75 words).

Another possibility is to try to reverse-engineer the javascript code (or evaluate it somehow) behind the Tokenizer tool. The code looks it is not making any network request, so all the logic for the tokenization is performed client-side, however all the javascript is obfuscated and minified.

**Comment by nicolaparo** [comment]
Sorry, my bad. I reviewed my C# implementation that was correctly working with English (IDK why it was working at this point), and I found out that it actually works also with strings of different languages also. My mistake was due to the fact that the javascript implementation of `str.split('')` and the C# version `str.Split("")` actually return completely different results.

**Comment by nicolaparo** [comment]
Sure, here you are! I tried it using Polyglot Notebooks. 

The first example shows str.Split("") in C#, the second one the same code but in javascript.

In C# the result is an array with only one item, meanwhile in javascript is an array with a string per each character of the original string

![image](https://user-images.githubusercontent.com/50980836/226434116-93efea79-2fea-4688-947a-e384228fe890.png)

**Comment by nicolaparo** [comment]
We should discuss where the `vocab.bpe` and the `encodings.json` should be provided to the method. I was thinking about a static method that can be used to create the singleton for retrieving the token amount

```csharp
var tokenizer = await GPTTokenizer.CreateTokenizerAsync(
    bpeVocabStream: File.OpenRead(@"vocab.bpe"),
    encoderJsonStream: File.OpenRead(@"encoder.json"),
    tokenizerType: GPTTokenizerType.Gpt3
);

var test = @"Qual è la città più popolosa d'Italia?";
var tokenCount = tokenizer.GetTokens(test).Length;

Console.WriteLine($"Test: {test}"); 
Console.WriteLine($"Potential cost: {tokenCount}");

// === Prints out as follows ===
// Test: Qual è la città più popolosa d'Italia?
// Potential cost: 18
```
Can we proceed with something like that? I expect then this class to be a singleton handled by the `ChatGptClient` class internally.

**Comment by marcominerva** [comment]
I wouldn't like to add such dependencies to the library.
 
I have just found this method by @timheuer: https://gist.github.com/timheuer/36e941b6ea601ea4ee8be2c285ca4490, peraphs we can give it a try. We just need an estimate, if we reach the same order of magnitude of the official solution, I think will be fine.

**Comment by nicolaparo** [comment]
Unfortunately there is no way to estimate correctly the token cost without including the dependencies to these dictionary files.

I created this repo with the implementation of the Tokenizer: https://github.com/nicolaparo/ChatGptNet.Tokenizer
Of course, it is still in an early stage, so contributions are welcomed. 

A nuget package is also available https://www.nuget.org/packages/ChatGptNet.Tokenizer/

**Comment by marcominerva** [comment]
Good solution @nicolaparo! What do you think about adding to your library an extension method on the `IChatGtpClient` to make estimation easier?

**Comment by timheuer** [comment]
Also see this Tokenizer: https://github.com/dluc/openai-tools
